image: Visual Studio 2017
init:
  - git config --global core.autocrlf input

build_script:
  - cmd: build.cmd BuildPackage

test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
  - path: bin_netcore
    name: bin_netcore
  - path: 'temp\*.nupkg'
    type: NuGetPackage
nuget:
  account_feed: false
  project_feed: true

environment:
  matrix:
    # run .net integration tests
    - SkipIntegrationTestsNetCore: true
      PAKET_TESTSUITE_FLAKYTESTS: false
    # run .net core integration tests
    - SkipIntegrationTestsNet: true
      PAKET_TESTSUITE_FLAKYTESTS: false
    # just flaky tests
    - PAKET_TESTSUITE_FLAKYTESTS: true

matrix:
  allow_failures:
    - PAKET_TESTSUITE_FLAKYTESTS: true

on_finish:
  - ps: >-
      $wc = New-Object 'System.Net.WebClient';
      $testResults = @(
        '.\tests_result\net\Paket.Tests\TestResult.xml'
        '.\tests_result\net\Paket.IntegrationTests\TestResult.xml'
        '.\tests_result\netcore\Paket.Tests\TestResult.trx'
        '.\tests_result\netcore\Paket.IntegrationTests\TestResult.trx'
      )
  - ps: >-
      Foreach ($path in $testResults) {
        If (Test-Path $path) {
          $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $path))
        }
      }
